Update .drone.yml

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -2,73 +2,60 @@ kind: pipeline
 type: docker
 name: build
 steps:
+  name: dummy-echo
+  image: alpine:latest
+  commands:
+    - echo "build step taking 10s."
+    - sleep 10
 
-name: dummy-echo
-image: alpine:latest
-commands:
-
-echo "build step taking 10s."
-
-sleep 10
-—
+---
 kind: pipeline
 type: docker
 name: test
 steps:
+  - name: dummy-echo
+    image: alpine:latest
+    commands:
+      - echo "sleep 10s and fail."
+  - name: sleep
+    image: alpine:latest
+    commands:
+      - sleep 5
+  - name: fail
+    image: alpine:latest
+    commands:
+    - exit 1
+--- 
 
-name: dummy-echo
-image: alpine:latest
-commands:
-
-echo "sleep 10s and fail."
-
-name: sleep
-image: alpine:latest
-commands:
-
-sleep 5
-
-name: fail
-image: alpine:latest
-commands:
-
-exit 1
-—
 kind: pipeline
 type: docker
 name: tools
 steps:
+  name: dummy-echo
+  image: alpine:latest
+  commands:
+    - echo "This is a fast pipeline with success."
 
-name: dummy-echo
-image: alpine:latest
-commands:
-
-echo "This is a fast pipeline with success."
-—
+---
 kind: pipeline
 type: docker
 name: deploy
 steps:
-
-name: dummy-echo
-image: alpine:latest
-commands:
-
-echo "This is a dummy fast step."
+  name: dummy-echo
+  image: alpine:latest
+  commands:
+    - echo "This is a dummy fast step."
 depends_on:
+ - build
 
-build
-—
+---
 kind: pipeline
 type: docker
 name: perf
 steps:
-
-name: dummy-echo
-image: alpine:latest
-commands:
-
-echo "This is a dummy fast step."
+  name: dummy-echo
+  image: alpine:latest
+  commands:
+    - echo "This is a dummy fast step."
 depends_on:
-
-build
+  -  build
